#!/bin/sh /etc/rc.common

START=61
STOP=00

PROG=/usr/sbin/kresd
CONFIGFILE=/etc/knot-resolver/kresd.config
DEFAULT_RUNDIR=/tmp/kresd
USERNAME=kresd
GROUP=kresd

modify_rundir() {
        local rundir

        #create rundir
        rundir="$DEFAULT_RUNDIR"

        if [ ! -d "$rundir" ]; then
                mkdir -p "$rundir"
        fi

        if id "$1" >/dev/null 2>&1; then
                chown -R $USERNAME:$GROUP "$rundir"
        fi
}

start_service() {
        procd_open_instance
        procd_set_param command "$PROG"
        procd_append_param command --noninteractive
        procd_set_param respawn
        modify_rundir

        # knot-resolver config
        procd_append_param command -c "$CONFIGFILE"
        procd_set_param nice '-5'
        procd_close_instance
}

reload_service()
{
        stop
        start
}
