#!/bin/bash

logger "the button was ${BUTTON} and the action was ${ACTION}"

NUMBER="$(uci get system.@system[0].cronloglevel)"

if [[ "$ACTION" == "released"  ]] ; then
        exit
fi

if [[ $NUMBER -eq 5 ]] ; then
        bash /etc/script_network_wireguard_cloud_change.sh 1

        sleep 20
        uci set system.@system[0].cronloglevel=6
        uci del sqm.eth1.qdisc_really_really_advanced
        uci set sqm.eth1.interface='sfp1'
        uci set network.wan.ac_mac='f4:de:af:d8:22:ff'
        nohup  einat -i pppoe-wan --hairpin-if lo br-lan >& nohup.out &
        uci commit
        service sqm restart
        service system restart

else
        bash /etc/script_network_wireguard_cloud_change.sh 2
        /etc/init.d/wireguard_cloud restart

        sleep 20
        uci set system.@system[0].cronloglevel=5
        uci set sqm.eth1.interface='cloud'
        uci set network.wan.ac_mac='f4:de:af:d8:22:ff'
        nohup  einat -i cloud --hairpin-if lo br-lan >& nohup.out &
        uci commit
        service sqm restart
        service system restart
fi
