#!/bin/bash

#logger "the button was ${BUTTON} and the action was ${ACTION}"

NUMBER="$(uci get system.@system[0].cronloglevel)"

if [[ "$ACTION" == "released"  ]] ; then
        exit
fi

if [[ $NUMBER -eq 7 ]] ; then
        bash /etc/scripts/script_network_wireguard_cloud_change.sh 1

        uci set system.@system[0].cronloglevel=5
        uci commit
        service system restart
        service network restart

elif [[ $NUMBER -eq 5 ]] ; then
        bash /etc/scripts/script_network_wireguard_cloud_change.sh 2

        uci set system.@system[0].cronloglevel=6
        uci commit
        service system restart
        service network restart
        #/etc/init.d/wireguard_cloud restart
elif [[ $NUMBER -eq 6 ]] ; then
        bash /etc/scripts/script_network_wireguard_cloud_change.sh 3

        uci set system.@system[0].cronloglevel=7
        service system restart
        service network restart
        #/etc/init.d/wireguard_cloud restart
fi
