#!/bin/bash

logger "the button was ${BUTTON} and the action was ${ACTION}"

NUMBER="$(uci get system.@system[0].cronloglevel)"

if [[ "$ACTION" == "released"  ]] ; then
        exit
fi

if [[ $NUMBER -eq 7 ]] ; then
        bash /etc/script_network_wireguard_cloud_change.sh 1

        uci set system.@system[0].cronloglevel=5
        uci del sqm.eth1.qdisc_really_really_advanced
        uci set sqm.eth1.interface='sfp1'
        uci commit
        service sqm restart
        service system restart
        service network restart

elif [[ $NUMBER -eq 5 ]] ; then
        bash /etc/script_network_wireguard_cloud_change.sh 2

        uci set system.@system[0].cronloglevel=6
        uci set sqm.eth1.interface='cloud'
        uci commit
        service sqm restart
        service system restart
        /etc/init.d/wireguard_cloud restart
elif [[ $NUMBER -eq 6 ]] ; then
        bash /etc/script_network_wireguard_cloud_change.sh 3

        uci set system.@system[0].cronloglevel=7
        uci set sqm.eth1.interface='cloud'
        uci commit
        service sqm restart
        service system restart
        /etc/init.d/wireguard_cloud restart
fi
